//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_Youyous_MLaribi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commandes
    {
        public Commandes()
        {
            this.DetailsCommandes = new HashSet<DetailsCommandes>();
        }
    
        public int no { get; set; }
        public System.DateTime dateCommande { get; set; }
        public decimal total { get; set; }
        public string pseudo { get; set; }
    
        public virtual Usagers Usagers { get; set; }
        public virtual ICollection<DetailsCommandes> DetailsCommandes { get; set; }
    }
}
