//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_Youyous_MLaribi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagasinJouetsEntities1 : DbContext
    {
        public MagasinJouetsEntities1()
            : base("name=MagasinJouetsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commandes> Commandes { get; set; }
        public virtual DbSet<DetailsCommandes> DetailsCommandes { get; set; }
        public virtual DbSet<Skis> Skis { get; set; }
        public virtual DbSet<Usagers> Usagers { get; set; }
    }
}
