//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_Youyous_MLaribi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skis
    {
        public Skis()
        {
            this.DetailsCommandes = new HashSet<DetailsCommandes>();
        }
    
        public int id { get; set; }
        public string pseudo { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
        public System.DateTime dateFabrication { get; set; }
        public string details { get; set; }
        public decimal prix { get; set; }
    
        public virtual ICollection<DetailsCommandes> DetailsCommandes { get; set; }
        public virtual Usagers Usagers { get; set; }
    }
}
