//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP3_Youyous_MLaribi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usagers
    {
        public Usagers()
        {
            this.Commandes = new HashSet<Commandes>();
            this.Skis = new HashSet<Skis>();
        }
    
        public string pseudo { get; set; }
        public string motPasse { get; set; }
        public string type { get; set; }
        public string prenom { get; set; }
        public string nom { get; set; }
        public string adresse { get; set; }
        public string ville { get; set; }
        public string codePostal { get; set; }
        public string téléphone { get; set; }
    
        public virtual ICollection<Commandes> Commandes { get; set; }
        public virtual ICollection<Skis> Skis { get; set; }
    }
}
